FROM confluentinc/cp-kafka-connect:7.9.5

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.1.4
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.0