services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  api:
    image: amazoncorretto:23-alpine
    container_name: api
    depends_on:
      - mysql
    profiles: ["prod"]
    ports:
      - "8080:8080"
    volumes:
      - ./api/target/api-0.0.1-SNAPSHOT.jar:/app/api-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/api-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vollmed_api
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass

volumes:
  mysql_data:
