# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Integração Contínua


on:
  push:
    branches: [ "main" ]
    paths:
      - "32 - Integração Contínua pipelines e testes automatizados com GitHub Actions/3983-integracao-continua-projeto_inicial/**"
      - "!**/*.md"
  pull_request:
    branches: [ "main" ]
    paths:
      - "32 - Integração Contínua pipelines e testes automatizados com GitHub Actions/3983-integracao-continua-projeto_inicial/**"
      - "!**/*.md"

jobs:

  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "32 - Integração Contínua pipelines e testes automatizados com GitHub Actions/3983-integracao-continua-projeto_inicial"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: |
          32 - Integração Contínua pipelines e testes automatizados com GitHub Actions/3983-integracao-continua-projeto_inicial/go.sum


    - name: Inicia Banco
      run: docker compose up -d postgres

    - name: Lint
      run: docker run --rm -it -v "${pwd}:/app" -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

    - name: Test
      run: go test -v main_test.go