# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Integração Contínua


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "32_Integracao_Continua_pipelines_e_testes_automatizados_com_GitHub_Actions/3983-integracao-continua-projeto_inicial"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: |
          32_Integracao_Continua_pipelines_e_testes_automatizados_com_GitHub_Actions/3983-integracao-continua-projeto_inicial/go.sum


    - name: Inicia Banco
      run: docker compose up -d postgres

    - name: Esperando pelo Postgres
      run: |
        for i in {1..30}; do
          docker compose exec -T postgres pg_isready -U ${{secrets.DB_USER}} -d ${{secrets.DB_NAME}} && exit 0
          sleep 2
        done
        docker compose logs postgres
        exit 1

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: "32_Integracao_Continua_pipelines_e_testes_automatizados_com_GitHub_Actions/3983-integracao-continua-projeto_inicial"
        args: ./controllers/ ./database/ ./models/ ./routes/
      #run: docker run --rm -it -v "${pwd}:/app" -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

    - name: Test
      run: DB_HOST=${{secrets.DB_HOST}} DB_PASSWORD=${{secrets.DB_PASSWORD}} DB_USER=${{secrets.DB_USER}} DB_NAME=${{secrets.DB_NAME}} DB_PORT=${{secrets.DB_PORT}} go test -v main_test.go

    - name: Build
      run: go build main.go

    - name: Projeto compilado
      uses: actions/upload-artifact@v4
      with:
        name: projeto_compilado
        path: 32_Integracao_Continua_pipelines_e_testes_automatizados_com_GitHub_Actions/3983-integracao-continua-projeto_inicial/main